import React from 'react';

interface FooterProps {
  logoUrl?: string;
  showPageNumber?: boolean;
}

export default function Footer({ logoUrl, showPageNumber = true }: FooterProps) {
  return (
    <footer className="hidden print:flex justify-between items-center px-8 py-4 border-t border-gray-300 text-sm text-gray-600">
      <div className="flex items-center gap-3">
        {logoUrl && (
          <img src={logoUrl} alt="Impact3" className="h-6 w-auto" />
        )}
        <span className="font-semibold">Impact3</span>
        <span className="text-gray-400">|</span>
        <span>Capital Markets Marketing & Investor Relations</span>
      </div>

      {showPageNumber && (
        <div className="page-number">
          {/* Page number will be auto-generated by browser print */}
        </div>
      )}
    </footer>
  );
}
