// Export all report components for easier imports
export { default as CoverPage } from './CoverPage';
export { default as ExecutiveSummary } from './ExecutiveSummary';
export { default as TableOfContents } from './TableOfContents';
export { default as Section } from './Section';
export { default as DataTable } from './DataTable';
export { default as StatCard } from './StatCard';
export { default as Callout } from './Callout';
export { default as KeyFinding } from './KeyFinding';
export { default as PerformanceChart } from './PerformanceChart';
export { default as Footer } from './Footer';
